### ISSUE TITLE
Python 3.7 support request

### ISSUE THREAD

**Issue by Youjin1985** [materialsproject/api#600] opened 2022-05-16 03:15 UTC
Hello,
Please consider keeping support for 3.7. Many distributions and projects still use it, and 3.8 numpy has some terrible problems like this: https://github.com/MaartenGr/BERTopic/issues/392#issue-1092483558

**Comment by sgbaird** [comment] 2022-06-04 18:50
Agreed. For me, Google Colab is an important way that I expose code examples:
`crabnet` [![Open In Colab
(PyPI)](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sparks-baird/CrabNet/blob/main/examples/crabnet_basic_colab.ipynb) `mat_discover` [![Open In Colab (PyPI)](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1MgV_ZewS6gLm1a3Vyhg33pFHi5uTld_2?usp=sharing) `xtal2png` [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sparks-baird/xtal2png/blob/main/notebooks/1.0-xtal2png-tutorial.ipynb)

It also makes it nice for sharing or requesting reproducers (e.g. https://github.com/facebook/Ax/issues/743#issuecomment-1082561142)

Google Colab runs on Python 3.7, and while there are [workarounds for installing Python 3.8](https://stackoverflow.com/a/63797862/13697228), they're clunky at best --> "hack to install Anaconda" --> "Install Python 3.8 through Anaconda" with [some solutions working and then becoming defunct](https://stackoverflow.com/a/63799569/13697228) and almost always requiring a restart of the kernel (source of confusion) and reinstalling many packages from scratch.

Any idea what it would take to support Python 3.7 in terms of refactoring code?

**Comment by sgbaird** [comment] 2022-06-04 18:57
I'm noticing that `pymatgen==2022.5.26` (latest) depends on `python >=3.8` according to the Win64 Anaconda distribution info on `conda-forge`. So, this is probably a much bigger issue and may not be feasible.

@Youjin1985 incidentally the same issue seems to have cropped up for `pymatgen` with numpy issues https://github.com/materialsproject/pymatgen/issues/2333

**Comment by sgbaird** [comment] 2022-06-04 19:07
Related:
- https://github.com/materialsproject/pymatgen/issues/2071#issuecomment-782315904
- https://github.com/materialsproject/pymatgen/issues/2071#issuecomment-782316707

**Comment by sgbaird** [comment] 2022-06-04 20:06
Planning to make `mp-api` an optional dependency for [mp-time-split](https://github.com/sparks-baird/mp-time-split) which I think is a good compromise considering the intended use-case. Will stick it out with the new API 👍 

Made a [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sparks-baird/mp-time-split/blob/main/notebooks/other/mp-api-colab-py38.ipynb) example of running `mp-api`, it takes ~20 minutes, requires kernel restarts, and browser refreshing to get to the first `MPRester` statement and supposedly has to be a copy of that exact notebook due to internal metadata (i.e. can't copy-paste the code to another notebook and have it run) 😅

The first few statements can be condensed to a single cell of course.

**Comment by munrojm** [comment] 2023-05-16 21:45
Closing as collab has updated their python version.

**Closed by munrojm** 2023-05-16 21:45 UTC
